FROM mcr.microsoft.com/playwright:latest
RUN \
	apt-get -y update && \
	apt-get -y dist-upgrade && \
	apt-get -y install python3 python3-pip

COPY requirements.txt .
COPY test-requirements.txt .
RUN \
	pip install --upgrade pip setuptools wheel && \
	pip install --upgrade --use-pep517 -r requirements.txt && \
	pip install --upgrade --use-pep517 -r test-requirements.txt && \
	python3 -m playwright install
